### ISSUE TITLE
Provide more documentation on source code protection

### ISSUE THREAD

**Issue by stefreak** [step-security/harden-runner#170]
In one of my jobs I expected harden-runner to fail the job as I overwrite the source code using sed in one of the shell steps. But nothing happened with `egress-policy: audit`

How does the source code protection work, what does it protect against exactly?

Will it warn / inform about source code being overwritten, or does it block the system call? Does that depend on the setting of the egress-policy?

Is it allowed to create new files, or I just can't overwrite existing files? Is there a way to provide a white-list of files allowed to be overwritten by a certain step?

Keep on with the great work, thanks a lot for `harden-runner`

**Comment by stefreak** [comment]
This example demonstrates the behaviour that is unexpected for me, after reading the README in harden-runner

Expected behaviour: it should fail as it overwrites source code
Observed behaviour: It succeeds 

Unfortunately I can't see wether harden-runner observed that source code has been written at all, because of #171

```
on:
  push:

jobs:
  trigger-code-protection:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
      with:
        egress-policy: audit

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

    - name: Malicious script (Could be part of an NPM hook etc)
      run: |
        echo "Malicios code" >> README.md
```

**Comment by varunsh-coder** [comment]
Hi @stefreak, thanks for creating the issue! I agree we need to improve the documentation for this scenario. 

1. Detecting overwriting of source code only checks for a subset of file extensions right now. 
2. These files extensions are `".c", ".cpp", ".cs", ".go", ".java"`. Here is the source code. 
https://github.com/step-security/agent/blob/7175bea8d3022069ad6c510207dd4f0f51066ead/eventhandler.go#L107-L119
4. We had a larger set of extensions earlier, but it created lot of noise, so we decided to reduce them and then tune it and add more slowly. 
5. We have been thinking of adding more options so users can decide what extensions do they want to detect, or if they want to disable this check all together, to balance finding issues vs generating noise, but we also want to keep the overall usage simple. 

Please do share your suggestions. Thanks!

**Comment by stefreak** [comment]
I see! Thank you a lot for the quick explanation.

**Comment by stefreak** [comment]
Another thing I did not expect is, that overwriting code is actually not blocked, but there is only a warning in the GitHub workflow, see this workflow:
```
on:
  push:

jobs:
  trigger-code-protection:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
      with:
        egress-policy: audit

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

    - name: Malicious script (Could be part of an NPM hook etc)
      run: |
        echo "Malicios code" >> test.go
        echo "Exit code: $?"
```

It logs that the exit code is zero.

This means for fully automated releases, we rely on a human noticing the error message in the GitHub workflow UI at some point.
