### ISSUE TITLE
Add policy input

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/harden-runner#26]
```
- uses: step-security/harden-runner@main
   with:
    allowed-endpoints:
      api.github.com:443

AND

- uses: step-security/harden-runner@main
   with:
    policy: audit
```
