### ISSUE TITLE
Please whitelist *.actions.githubusercontent.com

### ISSUE THREAD

**Issue by jauderho** [step-security/harden-runner#331]
It appears that GitHub has started using this subdomain for actions related work. I've had to whitelist a few subdomains already and it'd be nice if the entire subdomain is whitelisted. 

Thanks.

See https://github.com/jauderho/dockerfiles/actions/runs/5746340561 for example.

**Comment by varunsh-coder** [comment]
Thanks for reporting @jauderho. It will be done as part of the next release.

**Comment by christophetd** [comment]
For the record, this issue broke a number of GitHub Actions that just became completely unresponsive e.g. https://github.com/DataDog/stratus-red-team/actions/runs/5974891989 and failed after 30+ minutes

<img width="1603" alt="image" src="https://github.com/step-security/harden-runner/assets/136675/6ffb861d-10e8-4478-84d7-2de529c7e2b5">

Upgrading to v2.5.1 was **not** enough, it seems that I had to explicitly allow the new endpoint in my configuration:

``` yaml
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
        with:
          egress-policy: block
          allowed-endpoints: >
            ...
            *.actions.githubusercontent.com:443
```
