### ISSUE TITLE
Harden runner causing DNS timeouts in containers

### ISSUE THREAD

**Issue by cpuguy83** [step-security/harden-runner#492]
In my setup, we are adding harden-runner as a first step.
Then I reconfigure dockerd to enable the containerd image store and as such restart docker.
After this, I get DNS issues in my containers that I am trying to build in.

Notably, its not just restarting docker that does this as I was already doing this to add some extra envs to the dockerd service unit.
This was not a problem.
Its specifically a problem when I configure docker to use containerd for the image store.

No problem if I stop using harden-runner and also no problem if, instead of disabling harden-runner, I just don't change to the containerd image store.
What's weird here is there really shouldn't be any difference in networking here, under the hood in docker its all the same.

```yaml
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

```

This step causes DNS resolution in the build (inside a container) to fail later, but *only* with harden-runner:

```
      - name: Configure dockerd
        run: |
          set -ex -o pipefail

          sudo mkdir -p /etc/docker
          jq . <<< '{ "features": {"containerd-snapshotter": true} }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
 ```

I've double-checked that there is no `daemon.json` in the GHA agent before, so I'm not overwriting anything.
I also checked to make sure there are no containers (running or otherwise) before I make the above change... which would make those containers disappear since its a different storage backend for docker.
