### ISSUE TITLE
Running the action optionally, including pre and post scripts

### ISSUE THREAD

**Issue by jenstroeger** [step-security/harden-runner#493]
We tried to make running Harden Runner optional:
```yaml
    steps:
    - name: Harden Runner
      if: ${{ vars.USE_HARDEN_RUNNER }}
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
      with:
        egress-policy: audit
```
However, this seems to impact only the main script and not the pre & post scripts https://github.com/step-security/harden-runner/blob/0080882f6c36860b6ba35c610c98ce87d4e2f26f/action.yml#L37-L39

Is there a way to en/disable all of them? The [`runs` documentation](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runs) mentions `pre-if` and `post-if` and I’m not quite sure if this is something we ought to implement, or the action? 

Do you guys have a suggestion?
