### ISSUE TITLE
harden runner not loading security console

### ISSUE THREAD

**Issue by Devils-Knight** [step-security/harden-runner#53]
> Demo Harden Runner workflow for nuget/setup-nuget
``` yml
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit
      - name: nuget/setup-nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
```
> Generated Workflow for nuget/setup-nuget

![image](https://user-images.githubusercontent.com/73299843/149379662-f8ba8237-c0a8-4bd7-b765-d14bba74d3fd.png)

> Output Step Security Console from harden-runner
https://app.stepsecurity.io/github/Devils-Knight/Knowledge-base/actions/runs/1693963110
![image](https://user-images.githubusercontent.com/73299843/149378842-e72ad29e-7404-4a95-a52f-ab8343133409.png)
