### ISSUE TITLE
harden-runner suggests `permissions: ''` which is invalid

### ISSUE THREAD

**Issue by jsoref** [step-security/harden-runner#538]
I added `step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1` per https://github.com/step-security/harden-runner/blob/617de1d11dea286f7a53941812f4667f646e72da/README.md?plain=1#L68-L71 in https://github.com/check-spelling-sandbox/crispy-train-expert-chainsaw/commit/226394965f1444ca661075c2bb5ecbb9ebd236f2 and visited the [recommendations](
https://app.stepsecurity.io/github/check-spelling-sandbox/crispy-train-expert-chainsaw/actions/runs/14498196346?tab=recommendations):

#### Recommended Configuration to Harden the Runner

- [x] Block egress traffic: Only allow calls to allowed endpoints
- [x] Monitor source code: Detect if source code is overwritten during build
- [ ] Disable sudo: Run the job without sudo access to the runner

Baseline of outbound destinations from the last 2 job runs. The baseline has not changed in the last 1 job runs.

```yaml
- name: Harden Runner
  uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
  with:
    egress-policy: block
    allowed-endpoints: >
      archive.ubuntu.com:443
      azure.archive.ubuntu.com:80
      esm.ubuntu.com:443
      packages.microsoft.com:443
```

#### Recommended job-level GITHUB_TOKEN Permissions
GITHUB_TOKEN Permissions are recommended based on the network and HTTPS events

```yaml
permissions: ''
```

----

I applied the recommended permissions in https://github.com/check-spelling-sandbox/crispy-train-expert-chainsaw/commit/5a97c625cb5d060772bcfc4234bba0cebefc1e6b
which resulted in https://github.com/check-spelling-sandbox/crispy-train-expert-chainsaw/actions/runs/14498280602:

Annotations
1 error
❌ [**Invalid workflow file: .github/workflows/apt.yml#L11**](https://github.com/check-spelling-sandbox/crispy-train-expert-chainsaw/actions/runs/14498280602/workflow)
>    `The workflow is not valid. .github/workflows/apt.yml (Line: 11, Col: 18): Unexpected value ''`
