### ISSUE TITLE
harden-runner suggests downgrading action

### ISSUE THREAD

**Issue by jsoref** [step-security/harden-runner#539]
I added `step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1` per https://github.com/step-security/harden-runner/blob/617de1d11dea286f7a53941812f4667f646e72da/README.md?plain=1#L68-L71 in https://github.com/check-spelling-sandbox/crispy-train-expert-chainsaw/commit/226394965f1444ca661075c2bb5ecbb9ebd236f2 and visited the [recommendations](
https://app.stepsecurity.io/github/check-spelling-sandbox/crispy-train-expert-chainsaw/actions/runs/14498196346?tab=recommendations):

#### Recommended Configuration to Harden the Runner

- [x] Block egress traffic: Only allow calls to allowed endpoints
- [x] Monitor source code: Detect if source code is overwritten during build
- [ ] Disable sudo: Run the job without sudo access to the runner

Baseline of outbound destinations from the last 2 job runs. The baseline has not changed in the last 1 job runs.

```yaml
- name: Harden Runner
  uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
  with:
    egress-policy: block
    allowed-endpoints: >
      archive.ubuntu.com:443
      azure.archive.ubuntu.com:80
      esm.ubuntu.com:443
      packages.microsoft.com:443
```
...

---

Two points:
1. If you're going to suggest a thing in a readme and then have the program suggest a thing, it's really nice if the syntaxes you use are consistent.
    The README -> Run behavior results in this diff:
    ```diff
    -    - uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1 
    +    - name: Harden Runner
    +      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
    ```

    It would be nicer if either the README suggested:
    ```yaml
        - name: Harden Runner
          uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1 
    ```
    Because, then when the run made a suggestion, the diff would be:
    ```diff
         - name: Harden Runner
    -      uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1 
    +      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
    ```

2. It'd be nice if the program didn't suggest downgrading at all. I'm not sure why it does.
