### ISSUE TITLE
allowed-endpoints should either be a list or use a block-style indicator

### ISSUE THREAD

**Issue by mjpieters** [step-security/harden-runner#82]
The `allowed_endpoints` block is, apparently, a blob of text. The recommendations output by the hardener look something like this:

```yaml
- name: Harden Runner
  uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
  with:
    egress-policy: block
    allowed-endpoints: 
      api.github.com:443
      artifactcache.actions.githubusercontent.com:443
      github.com:443
      kv4gacprodeus2file3.blob.core.windows.net:443
```

which my Visual Studio code editor then neatly reformats to:

```yaml
  - name: Harden Runner
    uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
    with:
      egress-policy: block
      allowed-endpoints: api.github.com:443
        artifactcache.actions.githubusercontent.com:443
        github.com:443
        kv4gacprodeus2file3.blob.core.windows.net:443
```

note that the `api.github.com:443` line has shifted up.

If the `allowed-endpoints` format were to be a list, the above would instead look like

```
- name: Harden Runner
  uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
  with:
    egress-policy: block
    allowed-endpoints: 
      - api.github.com:443
      - artifactcache.actions.githubusercontent.com:443
      - github.com:443
      - kv4gacprodeus2file3.blob.core.windows.net:443
```

or if a [block-style indicator for multi-line text](https://yaml-multiline.info/) was used, such as `>`:

```
- name: Harden Runner
  uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
  with:
    egress-policy: block
    allowed-endpoints: >
      api.github.com:443
      artifactcache.actions.githubusercontent.com:443
      github.com:443
      kv4gacprodeus2file3.blob.core.windows.net:443
```

Both formats are in canonical form and would not cause a reformat. I used the latter in my configurations.
