### ISSUE TITLE
Make it configurable, if mode is block, to not send telemetry to API

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/harden-runner#89]
When user sets this mode, e.g.

```
- name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: 
            github.com:443
```

agent should not make calls to `agent.api.stepsecurity.io`. 
Other allowed-endpoints can still be called. 

- [ ] Do not show link - clarify that insights will not be generated
- [ ] Add this attribute to the config
